# Generated by Django 3.0.3 on 2020-02-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('time', models.DateField()),
                ('comment', models.CharField(max_length=300, null=True)),
                ('happy', models.IntegerField(default=0)),
                ('sad', models.IntegerField(default=0)),
                ('calm', models.IntegerField(default=0)),
                ('excited', models.IntegerField(default=0)),
                ('bored', models.IntegerField(default=0)),
                ('nervous', models.IntegerField(default=0)),
                ('tired', models.IntegerField(default=0)),
                ('scared', models.IntegerField(default=0)),
                ('angry', models.IntegerField(default=0)),
            ],
        ),
    ]
